### ISSUE TITLE
add and expose etcdctl in k2cli tool

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken#109]
**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                                           |
| --------- | ------------------------------------------------------------------------------ |
| k2        | [samsung-cnct/k2cli](https://github.com/samsung-cnct/k2cli/issues/new)         |
| k2-charts | [samsung-cnct/k2-charts](https://github.com/samsung-cnct/k2-charts/issues/new) |
| k2-tools  | [samsung-cnct/k2-tools](https://github.com/samsung-cnct/k2-tools/issues/new)   |

**What keywords did you search in k2cli issues before filing this one?** (If you have found any duplicates, you should instead reply there.): none

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**k2cli version** (use `k2cli version`): all

**Environment**: blank

Please be sure not to submit any confidential information (e.g. ssh keys, provider secrets, etc.) as issues are publicly accessible.

- **Environment variables** (e.g. `env | grep 'KRAKEN_`):
- **Configuration files (`~/.kraken/config.yaml` or the file passed to `k2cli --config`) **:
- **Others**:

**What happened**:
feature request

**What you expected to happen**:
etcdctl should be available from the `k2cli tool` subcommand.  it should also, if possible, auto-load the correct SSL certs for the specified cluster.  this will, obviously, require the original output directory to be reachable.

**How to reproduce it** (as minimally and precisely as possible):
feature request

**Anything else we need to know**:
When this is complete we should add checking for etcdctl versions weekly.

**Comment by alejandroEsc** [comment]
I should be able to do so fairly quickly, and it will be useful for comcast also. Going to add myself to the ticket.
