### ISSUE TITLE
Revisit handling of environment vars, configuration etc using Viper and Cobra.

### ISSUE THREAD

**Issue by samba** [samsung-cnct/kraken#112]
**What keywords did you search in k2cli issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

- `viper`, `cobra`, `environment`, `Getenv`

---

*EDIT* updated for clarity. 

`k2cli` should adopt Viper integration properly for loading configuration. 

[Currently][2] we rely on `PreRunE` functions to specify configuration files, rather than relying on Viper's features. This currently presents as more boilerplate code, and may exhibit different behaviors than other applications' handling of configuration files, environment variables, and command line arguments. `k2cli` would benefit from integrating Viper's approach, providing more flexibility and consistency. 

The `careen` project provides a [good example of leveraging Viper][3].

[1]: https://github.com/samsung-cnct/k2cli/blob/d7454e05aab6b0a3078b660fb44497dfa25a853a/cmd/root.go#L201
[2]: https://github.com/samsung-cnct/k2cli/blob/d7454e05aab6b0a3078b660fb44497dfa25a853a/cmd/up.go#L35
[3]: https://github.com/samsung-cnct/careen/blob/c2212252557d0edf6ed0fdae549b98c42aca419a/cmd/root.go#L98

**Comment by coffeepac** [comment]
there are a number of people starting on new go projects so we should standardize this on k2cli and across all go projects.

**Comment by coffeepac** [comment]
@samba to take a look at careen for being a valid example of this

**Comment by davidewatson** [comment]
FWIW, [this](https://github.com/samsung-cnct/careen/blob/master/cmd/root.go#L47) is an example of how to use Viper to automatically chose between config files, environment variables, and args. We should be using the Get*() family of functions, for example,

```
outputDirectory := careenConfig.GetString("output.directory")
```

**Comment by samba** [comment]
Thanks @davidewatson I think that example satisfies the needs that induced this ticket; I'll include it in documentation updates soon.

**Comment by samba** [comment]
Clarifying the problem this issue should actually track...

The current `k2cli` code relies heavily on `PreRunE` functions to load configuration, rather than leveraging Viper properly. [Example](https://github.com/samsung-cnct/k2cli/blob/d7454e05aab6b0a3078b660fb44497dfa25a853a/cmd/up.go#L35)

The work for this issue should focus on restructuring `k2cli`'s acquisition of config/parameters/etc, to leverage Viper properly, in combination with Cobra. 

The [careen project](https://github.com/samsung-cnct/careen/blob/master/cmd/root.go#L47) provides a good example. (Thanks @davidewatson)

**Comment by davidewatson** [comment]
Part of the motivation of this ticket is to get rid of global variables. #138 gives an example of where they have bitten us. Ideally only the viper config object and `ExitCode` needs to be global. Even `ExitCode` can be removed if we use `RunE` and `SilenceUsage` where appropriate.

Cf. https://github.com/spf13/cobra/issues/340

**Comment by alejandroEsc** [comment]
I am taking over this ticket and doing additional refactoring. So major changes coming, if there are additional tickets referencing this material or are part of these changes please feel free to reference them here.
