### ISSUE TITLE
make release fails due to GOPATH

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken#128]
From the k2cli git clone, make release fails as the source path does not exist in $GOPATH.

```
$ make release         
Number of parallel builds: 8

-->     linux/amd64: _/home/jjulian/dev/k2cli
-->       linux/386: _/home/jjulian/dev/k2cli
-->    darwin/amd64: _/home/jjulian/dev/k2cli

3 errors occurred:
--> darwin/amd64 error: exit status 1
Stderr: can't load package: package _/home/jjulian/dev/k2cli: cannot find package "_/home/jjulian/dev/k2cli" in any of:
	/usr/lib/go/src/_/home/jjulian/dev/k2cli (from $GOROOT)
	/home/jjulian/.local/go/src/_/home/jjulian/dev/k2cli (from $GOPATH)
.
.
.
```

**Comment by coffeepac** [comment]
when checking out go code it is the responsibility of the developer to ensure their local environment is correct.  part of this correctness is that k2cli source code has been landed properly into the GOPATH.

We are explicitly not covering how to set your go development environment in this repo.  that is handled much better by the language maintainers.

However, it appears from that error message that if you moved your cloned repo to `/home/jjulian/.local/go/src/github.com/samsung-cnct/k2cli` you would be able to build successfully.

**Comment by joejulian** [comment]
Yes, but this could so easily be managed within the Makefile that I would disagree.

**Comment by coffeepac** [comment]
resolution is to include a golang container for building and cause the makefile to use that

**Comment by alejandroEsc** [comment]
@coffeepac whats a good way to test, for example, `make build` in this fashion. I was thinking we use docker in docker, but really would have to make sure its a custom image that also contains the make binary. Is it even something we want to test in jenkins for that matter?

**Comment by coffeepac** [comment]
I'm not terribly sure actually.  I was probably writing down notes during a grooming session. 

@mikeln or @joejulian can you help alejandro out?

**Comment by mikeln** [comment]
I'm not sure I understand @alejandroEsc question?

**Comment by alejandroEsc** [comment]
@mikeln so for full context:

Changed make file to build, compile, and install using a go-lang docker container. That way, you can go ahead and build without worrying bout gopath etc.. However because of this, when we test on jenkins we basically operate on two levels: OS leve (core os) that has no make file, and the container level, which does have make file (depends on image). For the former case i would need to run make on coreos, which doesnt exist, in the later docker in docker would be required. Currently trying to install the make binary via an ubuntu docker container. see if that works.

**Comment by mikeln** [comment]
I have an issue with the set up you created.  I understand your desired outcome, but I think we already had a better way to structure this.  (again... see golang-tools/example-project).  

As for the docker-in-docker issue...at least in jenkins.  You can just add the docker-client only to your pipeline step to allow you to execute docker commands.

**Comment by alejandroEsc** [comment]
So for this ticket, its very difficult for ci without doing docker in docker, and yeah there are ways to get a docker client socket into the docker container as a way to bypass this. However, after talking to @mikeln it has come to our attention that doing a build in this way is probably not the right approach, in fact we have no real pattern for doing this in general. I suggest we close this ticket and revisit if we feel its a rather important endeavor, we should include all parties who have had something to do with this discussion here. @davidewatson @joejulian thoughts?
