### ISSUE TITLE
Add junit to CI

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/kraken#141]
**Is this a BUG REPORT or FEATURE REQUEST?** feature request

**k2cli version** (use `k2cli version`): Current version (1.08)

**Environment**: I'm not sure what this means. 

**What happened**:
Creating the first CI run for k2cli, we tried to add junit to the test run. This ultimately caused some of the unit tests in the project to fail, with no error message in the output.

**What you expected to happen**:
The tests should have passed.

**How to reproduce it** (as minimally and precisely as possible):
Add junit as per PR #104 in some of the earlier commits; watch Jenkins report an unstable build.

**Comment by coffeepac** [comment]
this is a jenkins specific plugin.  we will not being using jenkins going forward, closing.
