### ISSUE TITLE
Decide on whether to test update action during CI run

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/kraken#142]
**Is this a BUG REPORT or FEATURE REQUEST?**: feature request, but more of a research/decision issue

K2cli has the ability to update nodes per the update action. Should we test this during CI?

Pros: It is a feature we offer; we should test it.
Cons: It can take a very long time to test this action (roughly ten minutes per node being updated). As well, since update happens via a change in the config file, CI needs a way to alter its own config file.

**Comment by coffeepac** [comment]
Yes.
