### ISSUE TITLE
[Feature Request ] Unit tests, git hooks, etc.. : Make sure we keep golang standards up.

### ISSUE THREAD

**Issue by alejandroEsc** [samsung-cnct/kraken#155]
**What keywords did you search in Kraken issues before filing this one?** (If you have found any duplicates, you should instead reply there.): None

---
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Kraken version** (use `kraken version`):

**Environment**:

Please be sure not to submit any confidential information (e.g. ssh keys, provider secrets, etc.) as issues are publicly accessible.

- **Environment variables** (e.g. `env | grep 'KRAKEN_`):
- **Configuration files (`~/.kraken/config.yaml` or the file passed to `kraken --config`) **:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**: Currently we do not have enough unit tests to cover code paths and we should have a script to run, including a git hook, to ensure that we satisfy certain golang standards.

**Comment by alejandroEsc** [comment]
from https://github.com/samsung-cnct/k2cli/issues/102 we want to ensure we run:
- gosimple
- golint

for checks. and fix any issues found by running these.

**Comment by alejandroEsc** [comment]
may use instead a similar strategy as make verify for k8s, see: https://github.com/kubernetes/kubernetes/pull/47673#issuecomment-309118930

**Comment by alejandroEsc** [comment]
Will be adding a unit tests PR soon to close this out.

**Comment by coffeepac** [comment]
will be carried on in other issues as appropriate.
