### ISSUE TITLE
Final cleanup of k2cli references

### ISSUE THREAD

**Issue by yenicapotediaz** [samsung-cnct/kraken#161]
Now that the name has been updated, update all references to old repo name and any other references to k2cli.

**Comment by davidewatson** [comment]
I think the README is the most important thing. As it is now, this is a very poor UX for new users. Fixing up all of the golang imports is less important and can be done later if it takes longer.

**Comment by yenicapotediaz** [comment]
There's a separate ticket for the README https://github.com/samsung-cnct/kraken/issues/160
While making that change I saw all the other stuff that needs to be updated so I made this ticket. It's a quick fix.
