### ISSUE TITLE
Client and server versions of Helm incompatible when bringing up 1.6 cluster with released kraken (v1.1.1)

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/kraken#172]
**What keywords did you search in Kraken issues before filing this one?** (If you have found any duplicates, you should instead reply there.): helm

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Kraken version** (use `kraken version`): `1.1.1`

**Environment**: Running ` kraken cluster up -c <configpath>` with k8s version 1.6

**What happened**: Charts will not install:
```TASK [roles/kraken.services : Install charts from registry] ********************
failed: [localhost] (item={u'chart': u'samsung_cnct/heapster', u'version': u'0.1.0-0', u'namespace': u'kube-system', u'registry': u'quay.io', u'name': u'heapster'}) => {"changed": true, "cmd": ["/opt/cnct/kubernetes/v1.6/bin/helm", "registry", "install", "quay.io/samsung_cnct/heapster@0.1.0-0", "--", "--name", "heapster", "--namespace", "kube-system", "--values", "/Users/guin/.kraken/guinsix/quay.io-heapster.helmvalues"], "delta": "0:00:04.181201", "end": "2017-09-22 17:06:11.933560", "failed": true, "item": {"chart": "samsung_cnct/heapster", "name": "heapster", "namespace": "kube-system", "registry": "quay.io", "version": "0.1.0-0"}, "rc": 1, "start": "2017-09-22 17:06:07.752359", "stderr": "usage: appr [-h]\n            {pull,run-server,show,inspect,list,delete-package,helm,version,logout,deploy,plugins,push,login,config,channel,jsonnet}\n            ...\nappr: error: \nmessage: 'Error: incompatible versions client[v2.6.1] server[v2.5.1]\n\n  '\n\nError: plugin \"registry\" exited with error", "stderr_lines": ["usage: appr [-h]", "            {pull,run-server,show,inspect,list,delete-package,helm,version,logout,deploy,plugins,push,login,config,channel,jsonnet}", "            ...", "appr: error: ", "message: 'Error: incompatible versions client[v2.6.1] server[v2.5.1]", "", "  '", "", "Error: plugin \"registry\" exited with error"], "stdout": "", "stdout_lines": []}
```

**What you expected to happen**: Charts should install, and kraken should come with the approriate helm version already

**How to reproduce it** (as minimally and precisely as possible):
- Use the latest kraken release (currently, 1.1.1), generate a config file, change the k8s version to 1.6.x (recommend .4 or .7 for patch as that is what the author of this issue tried)  and run `kraken cluster up` using that config.

**Anything else we need to know**:

**Comment by coffeepac** [comment]
this is probably a bug in kraken-lib and not kraken

**Comment by coffeepac** [comment]
this is actually a bug in kraken-tools I think, we need to install the registry plugin to all versions of helm and not only the system default.

**Comment by guineveresaenger** [comment]
Confirmed: The tiller deployment runs v 2.5.1.
Kraken-tools issue is [here](https://github.com/samsung-cnct/kraken-tools/issues/134).

**Comment by guineveresaenger** [comment]
When the kraken-tools issue is fixed, a new release of kraken should be cut.

**Comment by rguthriemsft** [comment]
I think I am hitting same issue trying to install a basic chart by running `heml install <mychart>`

I get the error `Error: incompatible versions client[v2.6.1] server[v2.5.1]`

Is there a workaround or am I stuck for now till this is fixed?

**Comment by guineveresaenger** [comment]
Hi @rguthriemsft - there is a workaround for now while we fix this.
Run `helm init --upgrade` which will upgrade the server version, and then you should be able to install charts. I hope that helps.

**Comment by joejulian** [comment]
> this is actually a bug in kraken-tools I think, we need to install the registry plugin to all versions of helm and not only the system default.

Unlikely. All versions of helm should use the plugin as the environment configures it to live in /etc/helm/plugins (in kraken-tools) and those environment variables are not version specific.

**Comment by joejulian** [comment]
This is an upstream bug:
https://github.com/app-registry/appr/issues/87

**Comment by coffeepac** [comment]
@joejulian I think we can close this issue as we have settled on a fully-functional workaround.  or do you want to leave it open for up-stream tracking purposes?

if its a tracking issue I'd like to kick it off the board and downgrade to a p2.

**Comment by joejulian** [comment]
track it
