### ISSUE TITLE
[FEATURE REQUEST] kraken tool kubeconfig

### ISSUE THREAD

**Issue by alejandroEsc** [samsung-cnct/kraken#177]
**What keywords did you search in Kraken issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubeconfig

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

Ability to use kraken to merge the config file of your choice to your kube config. This will help in the areas of helm and management in general. sub commands should include 

-merge
-remove
-backup (optional flag also when performing the above tasks)

**Comment by coffeepac** [comment]
this has a high risk of breaking the users environment, we are going to pass for now.
