### ISSUE TITLE
Running Kraken Update via the Docker image fails with AWS Permissions Error

### ISSUE THREAD

**Issue by lolimjake** [samsung-cnct/kraken#183]
**Kraken version** (use `kraken version`):
quay.io/samsung_cnct/k2   latest              8646493752e4        2 hours ago         1.09 GB

**Environment**:

docker version:
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

- **Environment variables** (e.g. `env | grep 'KRAKEN_`):

AWS_CREDENTIALS=/Users/jake.martin/.aws/credentials
AWS_CONFIG=/Users/jake.martin/.aws/config
K2OPTS=-v /Users/jake.martin/.kraken:/Users/jake.martin/.kraken -v /Users/jake.martin/.ssh:/Users/jake.martin/.ssh -v /Users/jake.martin/.aws:/Users/jake.martin/.aws -e HOME=/Users/jake.martin --rm=true -it
AWS_ROOT=/Users/jake.martin/.aws
AWS_SDK_LOAD_CONFIG=1
AWS_PROFILE=lab_Admin
AWS_REGION=us-west-2

- **Configuration files (`~/.kraken/config.yaml` or the file passed to `kraken --config`) **:

From: kube2az-lab.yaml

authentication:
        accessKey:
        accessSecret:
        credentialsFile: "/Users/jake.martin/.aws/credentials"
        credentialsProfile: "lab_Admin"

- **Others**:
from : ~/.aws/credentials

[lab_Admin]
aws_access_key_id =  **[REDACTED]**
aws_secret_access_key =  **[REDACTED]**
aws_session_token =  **[REDACTED]**
aws_security_token = **[REDACTED]**

**What happened**:
I received an "AWS was not able to validate the provided access credentials" error when trying to update my cluster at this step: TASK [kraken.ssh/kraken.ssh.aws : Gather inventory of all cluster nodes] 

**What you expected to happen**:
The update command to complete successfully

**How to reproduce it** (as minimally and precisely as possible):
This command fails:
`docker run $K2OPTS quay.io/samsung_cnct/k2:latest /kraken/bin/update.sh --nodepools clusterNodes --config $HOME/.kraken/kube2az-lab.yaml`

This command does not:
`docker run $K2OPTS -e AWS_ACCESS_KEY_ID=[REDACTED] -e AWS_SECRET_ACCESS_KEY=[REDACTED] -e AWS_SESSION_TOKEN=[REDACTED] quay.io/samsung_cnct/k2:latest /kraken/bin/update.sh --nodepools clusterNodes --config $HOME/.kraken/kube2az-lab.yaml`

**Anything else we need to know**:
I am trying to update the cluster to change their AWS instance size only

The credentials are valid - I can run `aws ec2 describe-region --region us-west-2` successfully from my computer and from within the docker container

The credentials are AWS temporary STS creds

**Comment by coffeepac** [comment]
Please check to see if your local docker daemon has "lost time".   You can check by running any image and executing `date`.  

If the date is within 5 minutes please paste the entire error.

**Comment by lolimjake** [comment]
My date is accurate:

jake.martin@lt-jmart15-mac:.kraken$ date -u
Thu Sep 28 20:57:13 UTC 2017
jake.martin@lt-jmart15-mac:.kraken$ docker run $K2OPTS quay.io/samsung_cnct/k2:latest /bin/sh
/kraken # date -u
Thu Sep 28 20:57:23 UTC 2017


Full error: 
TASK [kraken.ssh/kraken.ssh.aws : Gather inventory of all cluster nodes] ******************************************************************************************************************************************************************************************************************
failed: [localhost] (item={u'count': 5, u'name': u'etcd', u'keyPair': {u'kind': u'keyPair', u'privatekeyFile': u'/Users/jake.martin/.ssh/kube2az-dev', u'name': u'defaultKeyPair', u'publickeyFile': u'/Users/jake.martin/.ssh/kube2az-dev.pub'}, u'osConfig': {u'kind': u'os', u'name': u'defaultCoreOs', u'version': u'current', u'channel': u'stable', u'type': u'coreOs', u'rebootStrategy': u'off'}, u'containerConfig': {u'kind': u'container', u'runtime': u'docker', u'type': u'distro', u'name': u'defaultDocker'}, u'nodeConfig': {u'mounts': [{u'device': u'sdf', u'path': u'/var/lib/docker', u'forceFormat': True}, {u'device': u'sdg', u'path': u'/ephemeral', u'forceFormat': False}], u'kind': u'node', u'providerConfig': {u'subnet': [u'zone-1', u'zone-2'], u'tags': [{u'value': u'Cluster etcd', u'key': u'comments'}], u'enablePublicIPs': False, u'storage': [{u'type': u'ebs_block_device', u'opts': {u'encrypted': False, u'volume_type': u'gp2', u'device_name': u'sdf', u'volume_size': 20, u'snapshot_id': None, u'delete_on_termination': True}}, {u'type': u'ebs_block_device', u'opts': {u'encrypted': False, u'volume_type': u'gp2', u'device_name': u'sdg', u'volume_size': 10, u'snapshot_id': None, u'delete_on_termination': True}}], u'provider': u'aws', u'type': u'm4.large'}, u'name': u'defaultAwsEtcdNode'}, u'etcdConfig': {u'clientPorts': [2379, 4001], u'clusterToken': u'beer-is-good', u'kind': u'kvStore', u'name': u'etcd', u'ssl': True, u'version': u'v3.1.0', u'peerPorts': [2380], u'type': u'etcd'}}) => {"failed": true, "item": {"containerConfig": {"kind": "container", "name": "defaultDocker", "runtime": "docker", "type": "distro"}, "count": 5, "etcdConfig": {"clientPorts": [2379, 4001], "clusterToken": "beer-is-good", "kind": "kvStore", "name": "etcd", "peerPorts": [2380], "ssl": true, "type": "etcd", "version": "v3.1.0"}, "keyPair": {"kind": "keyPair", "name": "defaultKeyPair", "privatekeyFile": "/Users/jake.martin/.ssh/kube2az-dev", "publickeyFile": "/Users/jake.martin/.ssh/kube2az-dev.pub"}, "name": "etcd", "nodeConfig": {"kind": "node", "mounts": [{"device": "sdf", "forceFormat": true, "path": "/var/lib/docker"}, {"device": "sdg", "forceFormat": false, "path": "/ephemeral"}], "name": "defaultAwsEtcdNode", "providerConfig": {"enablePublicIPs": false, "provider": "aws", "storage": [{"opts": {"delete_on_termination": true, "device_name": "sdf", "encrypted": false, "snapshot_id": null, "volume_size": 20, "volume_type": "gp2"}, "type": "ebs_block_device"}, {"opts": {"delete_on_termination": true, "device_name": "sdg", "encrypted": false, "snapshot_id": null, "volume_size": 10, "volume_type": "gp2"}, "type": "ebs_block_device"}], "subnet": ["zone-1", "zone-2"], "tags": [{"key": "comments", "value": "Cluster etcd"}], "type": "m4.large"}}, "osConfig": {"channel": "stable", "kind": "os", "name": "defaultCoreOs", "rebootStrategy": "off", "type": "coreOs", "version": "current"}}, "msg": "AWS was not able to validate the provided access credentials"}
failed: [localhost] (item={u'count': 3, u'name': u'etcdEvents', u'keyPair': {u'kind': u'keyPair', u'privatekeyFile': u'/Users/jake.martin/.ssh/kube2az-dev', u'name': u'defaultKeyPair', u'publickeyFile': u'/Users/jake.martin/.ssh/kube2az-dev.pub'}, u'osConfig': {u'kind': u'os', u'name': u'defaultCoreOs', u'version': u'current', u'channel': u'stable', u'type': u'coreOs', u'rebootStrategy': u'off'}, u'containerConfig': {u'kind': u'container', u'runtime': u'docker', u'type': u'distro', u'name': u'defaultDocker'}, u'nodeConfig': {u'mounts': [{u'device': u'sdf', u'path': u'/var/lib/docker', u'forceFormat': True}, {u'device': u'sdg', u'path': u'/ephemeral', u'forceFormat': False}], u'kind': u'node', u'providerConfig': {u'subnet': [u'zone-1', u'zone-2'], u'tags': [{u'value': u'Cluster events etcd', u'key': u'comments'}], u'enablePublicIPs': False, u'storage': [{u'type': u'ebs_block_device', u'opts': {u'encrypted': False, u'volume_type': u'gp2', u'device_name': u'sdf', u'volume_size': 20, u'snapshot_id': None, u'delete_on_termination': True}}, {u'type': u'ebs_block_device', u'opts': {u'encrypted': False, u'volume_type': u'gp2', u'device_name': u'sdg', u'volume_size': 10, u'snapshot_id': None, u'delete_on_termination': True}}], u'provider': u'aws', u'type': u'm4.large'}, u'name': u'defaultAwsEtcdEventsNode'}, u'etcdConfig': {u'clientPorts': [2381], u'clusterToken': u'fabric-i-love', u'kind': u'kvStore', u'name': u'etcdEvents', u'ssl': True, u'version': u'v3.1.0', u'peerPorts': [2382], u'type': u'etcd'}}) => {"failed": true, "item": {"containerConfig": {"kind": "container", "name": "defaultDocker", "runtime": "docker", "type": "distro"}, "count": 3, "etcdConfig": {"clientPorts": [2381], "clusterToken": "fabric-i-love", "kind": "kvStore", "name": "etcdEvents", "peerPorts": [2382], "ssl": true, "type": "etcd", "version": "v3.1.0"}, "keyPair": {"kind": "keyPair", "name": "defaultKeyPair", "privatekeyFile": "/Users/jake.martin/.ssh/kube2az-dev", "publickeyFile": "/Users/jake.martin/.ssh/kube2az-dev.pub"}, "name": "etcdEvents", "nodeConfig": {"kind": "node", "mounts": [{"device": "sdf", "forceFormat": true, "path": "/var/lib/docker"}, {"device": "sdg", "forceFormat": false, "path": "/ephemeral"}], "name": "defaultAwsEtcdEventsNode", "providerConfig": {"enablePublicIPs": false, "provider": "aws", "storage": [{"opts": {"delete_on_termination": true, "device_name": "sdf", "encrypted": false, "snapshot_id": null, "volume_size": 20, "volume_type": "gp2"}, "type": "ebs_block_device"}, {"opts": {"delete_on_termination": true, "device_name": "sdg", "encrypted": false, "snapshot_id": null, "volume_size": 10, "volume_type": "gp2"}, "type": "ebs_block_device"}], "subnet": ["zone-1", "zone-2"], "tags": [{"key": "comments", "value": "Cluster events etcd"}], "type": "m4.large"}}, "osConfig": {"channel": "stable", "kind": "os", "name": "defaultCoreOs", "rebootStrategy": "off", "type": "coreOs", "version": "current"}}, "msg": "AWS was not able to validate the provided access credentials"}
failed: [localhost] (item={u'count': 2, u'name': u'master', u'kubeConfig': {u'hyperkubeLocation': u'gcr.io/google_containers/hyperkube', u'kind': u'kubernetes', u'version': u'v1.6.4', u'name': u'defaultKube'}, u'keyPair': {u'kind': u'keyPair', u'privatekeyFile': u'/Users/jake.martin/.ssh/kube2az-dev', u'name': u'defaultKeyPair', u'publickeyFile': u'/Users/jake.martin/.ssh/kube2az-dev.pub'}, u'osConfig': {u'kind': u'os', u'name': u'defaultCoreOs', u'version': u'current', u'channel': u'stable', u'type': u'coreOs', u'rebootStrategy': u'off'}, u'containerConfig': {u'kind': u'container', u'runtime': u'docker', u'type': u'distro', u'name': u'defaultDocker'}, u'nodeConfig': {u'mounts': [{u'device': u'sdf', u'path': u'/var/lib/docker', u'forceFormat': True}], u'kind': u'node', u'providerConfig': {u'subnet': [u'zone-1', u'zone-2'], u'tags': [{u'value': u'Master instances', u'key': u'comments'}], u'enablePublicIPs': False, u'storage': [{u'type': u'ebs_block_device', u'opts': {u'encrypted': False, u'volume_type': u'gp2', u'device_name': u'sdf', u'volume_size': 50, u'snapshot_id': None, u'delete_on_termination': True}}], u'provider': u'aws', u'type': u'm4.large'}, u'name': u'defaultAwsMasterNode'}, u'apiServerConfig': {u'kind': u'apiServer', u'name': u'defaultApiServer', u'loadBalancerConfigs': {u'subnet': [u'public-a', u'public-c']}, u'state': {u'etcd': {u'clientPorts': [2379, 4001], u'clusterToken': u'beer-is-good', u'kind': u'kvStore', u'name': u'etcd', u'ssl': True, u'version': u'v3.1.0', u'peerPorts': [2380], u'type': u'etcd'}}, u'events': {u'etcd': {u'clientPorts': [2381], u'clusterToken': u'fabric-i-love', u'kind': u'kvStore', u'name': u'etcdEvents', u'ssl': True, u'version': u'v3.1.0', u'peerPorts': [2382], u'type': u'etcd'}}, u'loadBalancer': u'cloud'}}) => {"failed": true, "item": {"apiServerConfig": {"events": {"etcd": {"clientPorts": [2381], "clusterToken": "fabric-i-love", "kind": "kvStore", "name": "etcdEvents", "peerPorts": [2382], "ssl": true, "type": "etcd", "version": "v3.1.0"}}, "kind": "apiServer", "loadBalancer": "cloud", "loadBalancerConfigs": {"subnet": ["public-a", "public-c"]}, "name": "defaultApiServer", "state": {"etcd": {"clientPorts": [2379, 4001], "clusterToken": "beer-is-good", "kind": "kvStore", "name": "etcd", "peerPorts": [2380], "ssl": true, "type": "etcd", "version": "v3.1.0"}}}, "containerConfig": {"kind": "container", "name": "defaultDocker", "runtime": "docker", "type": "distro"}, "count": 2, "keyPair": {"kind": "keyPair", "name": "defaultKeyPair", "privatekeyFile": "/Users/jake.martin/.ssh/kube2az-dev", "publickeyFile": "/Users/jake.martin/.ssh/kube2az-dev.pub"}, "kubeConfig": {"hyperkubeLocation": "gcr.io/google_containers/hyperkube", "kind": "kubernetes", "name": "defaultKube", "version": "v1.6.4"}, "name": "master", "nodeConfig": {"kind": "node", "mounts": [{"device": "sdf", "forceFormat": true, "path": "/var/lib/docker"}], "name": "defaultAwsMasterNode", "providerConfig": {"enablePublicIPs": false, "provider": "aws", "storage": [{"opts": {"delete_on_termination": true, "device_name": "sdf", "encrypted": false, "snapshot_id": null, "volume_size": 50, "volume_type": "gp2"}, "type": "ebs_block_device"}], "subnet": ["zone-1", "zone-2"], "tags": [{"key": "comments", "value": "Master instances"}], "type": "m4.large"}}, "osConfig": {"channel": "stable", "kind": "os", "name": "defaultCoreOs", "rebootStrategy": "off", "type": "coreOs", "version": "current"}}, "msg": "AWS was not able to validate the provided access credentials"}
failed: [localhost] (item={u'count': 6, u'name': u'clusterNodes', u'kubeConfig': {u'hyperkubeLocation': u'gcr.io/google_containers/hyperkube', u'kind': u'kubernetes', u'version': u'v1.6.4', u'name': u'defaultKube'}, u'keyPair': {u'kind': u'keyPair', u'privatekeyFile': u'/Users/jake.martin/.ssh/kube2az-dev', u'name': u'defaultKeyPair', u'publickeyFile': u'/Users/jake.martin/.ssh/kube2az-dev.pub'}, u'osConfig': {u'kind': u'os', u'name': u'defaultCoreOs', u'version': u'current', u'channel': u'stable', u'type': u'coreOs', u'rebootStrategy': u'off'}, u'containerConfig': {u'kind': u'container', u'runtime': u'docker', u'type': u'distro', u'name': u'defaultDocker'}, u'nodeConfig': {u'mounts': [{u'device': u'sdf', u'path': u'/var/lib/docker', u'forceFormat': True}, {u'device': u'sde', u'path': u'/opt', u'forceFormat': True}], u'kind': u'node', u'providerConfig': {u'subnet': [u'zone-1', u'zone-2'], u'tags': [{u'value': u'Cluster plain nodes', u'key': u'comments'}], u'enablePublicIPs': False, u'storage': [{u'type': u'ebs_block_device', u'opts': {u'encrypted': False, u'volume_type': u'gp2', u'device_name': u'sdf', u'volume_size': 100, u'snapshot_id': None, u'delete_on_termination': True}}, {u'type': u'ebs_block_device', u'opts': {u'encrypted': False, u'volume_type': u'gp2', u'device_name': u'sde', u'volume_size': 15, u'snapshot_id': None, u'delete_on_termination': True}}], u'provider': u'aws', u'type': u'r4.4xlarge'}, u'name': u'defaultAwsClusterNode'}}) => {"failed": true, "item": {"containerConfig": {"kind": "container", "name": "defaultDocker", "runtime": "docker", "type": "distro"}, "count": 6, "keyPair": {"kind": "keyPair", "name": "defaultKeyPair", "privatekeyFile": "/Users/jake.martin/.ssh/kube2az-dev", "publickeyFile": "/Users/jake.martin/.ssh/kube2az-dev.pub"}, "kubeConfig": {"hyperkubeLocation": "gcr.io/google_containers/hyperkube", "kind": "kubernetes", "name": "defaultKube", "version": "v1.6.4"}, "name": "clusterNodes", "nodeConfig": {"kind": "node", "mounts": [{"device": "sdf", "forceFormat": true, "path": "/var/lib/docker"}, {"device": "sde", "forceFormat": true, "path": "/opt"}], "name": "defaultAwsClusterNode", "providerConfig": {"enablePublicIPs": false, "provider": "aws", "storage": [{"opts": {"delete_on_termination": true, "device_name": "sdf", "encrypted": false, "snapshot_id": null, "volume_size": 100, "volume_type": "gp2"}, "type": "ebs_block_device"}, {"opts": {"delete_on_termination": true, "device_name": "sde", "encrypted": false, "snapshot_id": null, "volume_size": 15, "volume_type": "gp2"}, "type": "ebs_block_device"}], "subnet": ["zone-1", "zone-2"], "tags": [{"key": "comments", "value": "Cluster plain nodes"}], "type": "r4.4xlarge"}}, "osConfig": {"channel": "stable", "kind": "os", "name": "defaultCoreOs", "rebootStrategy": "off", "type": "coreOs", "version": "current"}}, "msg": "AWS was not able to validate the provided access credentials"}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=116  changed=0    unreachable=0    failed=1

**Comment by coffeepac** [comment]
can you please try the newest release:  quay.io/samsung_cnct/k2:v0.3 ?  I cut this release, oh, 5 minutes ago.

**Comment by lolimjake** [comment]
Running this:  docker run $K2OPTS quay.io/samsung_cnct/k2:v0.3 /kraken/bin/update.sh --nodepools clusterNodes --config $HOME/.kraken/kube2az-lab.yaml

I get the same error in the same location

**Comment by coffeepac** [comment]
well nuts.  thank you.

**Comment by coffeepac** [comment]
I have replicated the issue locally and am now working on a solution.

**Comment by coffeepac** [comment]
@lolimjake can you give me the 10 lines before the failure message begins?  I think I know what the problem is.

**Comment by coffeepac** [comment]
my suspicion is that your config file needs to include `securityToken:` as a key in the `authentication:` stanza.  It should be empty but it needs to be present.

I also found another bug for which I opened up samsung-cnct/kraken-lib#857
