### ISSUE TITLE
[feature request] Do not use default config location

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/kraken#184]
**Kraken version** (use `kraken version`):1.1.2

**What happened**:
When failing to pass `--config` flag before specifying a config file path, kraken will attemt to use a default config file. This behavior appears on both `kraken cluster up` and `kraken cluster update`.

**What you expected to happen**:
Kraken should declare that failing to pass a flag is invalid.

**How to reproduce it** (as minimally and precisely as possible):
1. Build kraken
2. Attempt to run up a cluster without passing `--config` flag OR attempt to update an existing cluster without passing `--config` flag

**Anything else we need to know**:
Currently the docs do not reflect the necessity to pass `--config` to `update` action, which will definitely result in the behavior described above.
See also: #173

**Comment by coffeepac** [comment]
this is not a bug, this is a feature request and not one that I am sure we should do.  The default configuration file location is where kraken lands a generated configuration file.  Having a default config location is a normal/expected thing for applications to have.

is there a reason we shouldn't have a default config location?

**Comment by guineveresaenger** [comment]
Maybe my example is not clear.

Running
`kraken cluster up` without anything will attempt to use default config. This is expected.
`kraken cluster up --config <path to custom config file location>` will use specified config. This is also expected.
However, running
` kraken cluster up <path to custom config file location>` or any `kraken cluster up <foobar>` will attempt to use default config, purely because the user forgot to pass `--config`. I don't think it should. I have a default config sitting around, and I don't really want kraken to touch it on accident just because I forgot `--config`, especially since currently the docs don't mention passing `--config` to `update`. It would be better if kraken said "this is an unknown command; please do <example command>" instead.

**Comment by alejandroEsc** [comment]
Its a feature request. Also there is a few good reasons to do this.

- I dont want to encourage customers to keep using a default config file. It should be only a way to generate their config file.
- The switch of failure to find a config to using a default one is something that can easily be missed. Leading to time and confusion as to why things didnt happen and they realized it was because of the wrong config file.
- No we also have a good example of the error we can see: 
```jake.martin@lt-jmart15-mac:kube2az-lab$ kraken cluster update --config /Users/jake/martin/.kraken/kube2az-lab.yaml -v --update-nodepools clusterNodes
Using Kraken config file: /Users/jake.martin/.kraken/config.yaml 
Pulling image 'quay.io/samsung_cnct/k2:v0.2' █▒▒▒▒▒▒▒▒▒ ^C
jake.martin@lt-jmart15-mac:kube2az-lab$ cd ..
jake.martin@lt-jmart15-mac:.kraken$ rm -f config.yaml 
jake.martin@lt-jmart15-mac:.kraken$ kraken cluster update --config /Users/jake/martin/.kraken/kube2az-lab.yaml -v --update-nodepools clusterNodes
file /Users/jake.martin/.kraken/config.yaml does not exist```
It would be nice to stop full here and concentrate as to why this is occurring.

**Comment by guineveresaenger** [comment]
I don't necessarily want to advocate for doing away with the default config. I just don't want Kraken to translate `kraken cluster up foobar` to using the default config. Only `kraken cluster up` with nothing after it should do that.

**Comment by coffeepac** [comment]
ahh, yes, if there is extraneous junk kraken should be doing something intelligent with it (nothing and asking the user what they meant, probably) and just carrying on
