### ISSUE TITLE
Remove GOX dependency

### ISSUE THREAD

**Issue by alejandroEsc** [samsung-cnct/kraken#192]
**What keywords did you search in Kraken issues before filing this one?** (If you have found any duplicates, you should instead reply there.): GOX, 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request: Enhancement

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.
     We do not need gox any longer to perform cross platform compiling. Yes its true that gox can do so in parallel, but we do not compile so many os and arch types that this is a burdon

**Comment by alejandroEsc** [comment]
@mikeln sorry for the delay here is the ticket.

**Comment by mattfarina** [comment]
Out of curiosity, why removing gox?

**Comment by alejandroEsc** [comment]
Some reasons there

https://github.com/samsung-cnct/kraken/pull/191

mostly because we can do cross compilation as it stands right now, we dont need to do things in parallel another, and the fact that this is something we need to install as an additional dep for compiling.

**Comment by alejandroEsc** [comment]
Closing PR because of disagreement. Leaving ticket open as it should still be addressed.

**Comment by mattfarina** [comment]
Folks, I just became a committer on gox (write access/merge PRs/etc). If there is an issue with something in it please let me know as I'll be helping to maintain it now.

**Comment by philoserf** [comment]
What should be addressed? It is not clear from the comments.

**Comment by alejandroEsc** [comment]
We no longer need gox, at least, not for what we are using it for as go has this ability now and really this is over kill. However, a few people expressed that the make file should be addressed with someone with more experience. @philoserf love the icon, feel free to take on the ticket if you wish.

**Comment by mattfarina** [comment]
Note, I did some performance testing. It appears gox is faster (it does parallel builds) than a shell script that iterates over a set to do them in serial.

**Comment by alejandroEsc** [comment]
@mattfarina its true that it is faster, i think i make note of that above, but i dont think there is much to gain here, or at least at time i looked at this, i didn't there was.

**Comment by philoserf** [comment]
We are using the parallel build from goreleaser on a coming pull request and the parallel lint testing of gometalinter already.

**Comment by philoserf** [comment]
I’ll benchmark god vs the build part of gorealeaser.
