### ISSUE TITLE
Set cloud provider?

### ISSUE THREAD

**Issue by manojlds** [samsung-cnct/kraken#194]
Following the setup, I am not able to mount volumes that use AWS EBS:

`Unable to mount volumes for pod "mongo-controller-rdjw2_default": Cloud provider does not support volumes`

Digging into it, I see that the cloud-provider argument needs to be passed via hyperkube to make Kubernetes know about AWS. Is this not an issue with your setup?

**Comment by l337ch** [comment]
We are not using the cloud provider features within kraken at the moment. How are you attempting to use the AWS persistent volumes as documented here?https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/persistent-volumes.md

**Comment by manojlds** [comment]
Following these docs: http://kubernetes.io/v1.1/docs/user-guide/volumes.html#awselasticblockstore

**Comment by manojlds** [comment]
I was able to successfully get this going by adding proper IAM roles, and setting `--cluster-provider=aws`. If you think this can be added here, I can send a PR.

**Comment by l337ch** [comment]
Please submit a PR :)

**Comment by coffeepac** [comment]
k2 handles this out of the box if you're interested:  github.com/samsung-cnct/k2
