### ISSUE TITLE
mount files specified in command line arguments

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken#196]
**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                                           |
| --------- | ------------------------------------------------------------------------------ |
| kraken-lib     | [samsung-cnct/kraken-lib](https://github.com/samsung-cnct/kraken-lib/issues/new)         |
| kraken-charts | [samsung-cnct/k2-charts](https://github.com/samsung-cnct/k2-charts/issues/new) |
| kraken-tools  | [samsung-cnct/kraken-tools](https://github.com/samsung-cnct/kraken-tools/issues/new)   |

**What keywords did you search in Kraken issues before filing this one?** (If you have found any duplicates, you should instead reply there.): kubectl

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

if I run `kraken tool kubectl apply -f <some arbitrary file path>` I expect this to work.  Currently, the command line path isn't being parsed for files to mount into the running kraken-lib container.

**Kraken version** (use `kraken version`): 1.2.1

**Environment**: darwin

Please be sure not to submit any confidential information (e.g. ssh keys, provider secrets, etc.) as issues are publicly accessible.

- **Environment variables** (e.g. `env | grep 'KRAKEN_`):
- **Configuration files (`~/.kraken/config.yaml` or the file passed to `kraken --config`) **:
- **Others**:

**What happened**:
kubectl failed because kubectl couldn't find the file

**What you expected to happen**:
kubectl call to succeed because it could find the file

**How to reproduce it** (as minimally and precisely as possible):
run the above command

**Anything else we need to know**:

**Comment by alejandroEsc** [comment]
interesting point. So, I'm not sure which approach is best but here are some possible ways to do this, and im not saying these are the only ways: 

- Create new flag that points to the location of files to mount for deployment
- Override the kubectl apply function and then parse out the -f (but must then pass to kubectl)
- parse argument (get command and flags and arugment) to then mount the requested volume.

Either way the functionality to mount additional volumes exists not in kraken, so its a matter of determining what is the best approach.

**Comment by coffeepac** [comment]
my preference is to parse the command line and mount that directory/file much like we already do for the config file.  it seems to be consistent with how we do things and means we don't have to do much with arg mangling for kubectl
