### ISSUE TITLE
include estimated time and start time for each cluster operation with status message

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken#20]
as a usability improvement, we should include an estimated amount of time for each operation to complete.  specifically, the up and down operations can easily take up to 10 minutes.  Without some kind of note from the application I keep losing track of how long things are taking and I'm starting to think that k2cli is significantly slower (I doubt it is, merely my perception because there is no output for me to track)

**Comment by coffeepac** [comment]
current k2cli down run is going past 20 minutes.  this is usually a 10 minute operation

**Comment by DStorck** [comment]
hopefully this will be dealt with if we switch to showing how many steps in the process have been completed, as suggested in https://github.com/samsung-cnct/k2cli/issues/81
