### ISSUE TITLE
Warn user if kubernetes version is older than the default config

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken#212]
## FEATURE REQUEST

When a user runs kraken against a config file that has an older kubernetes version than our default config, the user should get a warning stating such and suggesting they update their config and use kraken update to update their cluster.

**Kraken version** (use `kraken version`):
<= 1.2.3

**Comment by DStorck** [comment]
and perhaps an even stronger warning / fail if they try to use a version we don't support at all anymore
