### ISSUE TITLE
Migrate CI from Jenkins to Gitlab

### ISSUE THREAD

**Issue by philoserf** [samsung-cnct/kraken#216]
- [x] create `.gitlab-ci.yaml` at project root from [template](https://github.com/samsung-cnct/solas-container/blob/master/.gitlab-ci.yml)
- [x] test and verify `.gitlab-ci.yml` works as expected
- [x] Remove the `Jenkinsfile` in the current repo
- [x] Check off this project on the [umbrella ticket](https://github.com/samsung-cnct/issues/issues/89)

**Comment by coffeepac** [comment]
I have taken this over.  almost done!

**Comment by coffeepac** [comment]
ToReview:
- release 1.2.4 was created using goreleaser which is a gitlab.ci thing  (ergo, we can now cut kraken releases from gitlab)

**Comment by cwazy1** [comment]
lgtm
