### ISSUE TITLE
Generated config should be complete with some default cluster name 

### ISSUE THREAD

**Issue by philoserf** [samsung-cnct/kraken#220]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**Kraken version**:

1.2.3-stable+git.sha.f855e5378bcf1d80ffbf441b8274e145cec1ce2e

**What happened**:

After running `kraken generate` the config MUST be edited before it can be used.

**What you expected to happen**:

Running `kraken generate` could produce a complete configuration with a required value for the cluster name.

**Anything else we need to know**:

This would also simplify the configuration rewrite `sed` command used in CI/CD.
Also reported at samsung-cnct/kraken-lib#995

**Comment by joejulian** [comment]
I think if we're going to provide the cluster name programatically, we should have a kraken generate flag that allows the user to specify the name, thus eliminating the need for sed altogether.
