### ISSUE TITLE
make brew upgrade kraken work

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/kraken#227]
currently running `brew upgrade kraken` results in: `Error: samsung-cnct/k2cli/kraken 64 already installed`

Either get this to properly upgrade to newest kraken version, or include some documentation in main readme about what the workaround should be.

**Comment by davidewatson** [comment]
I think this is a dup of https://github.com/samsung-cnct/homebrew-kraken/issues/21

**Comment by DStorck** [comment]
thanks, i had searched for `brew` and hadn't seen an issue, i will close it
