### ISSUE TITLE
add aws credential requirements

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken#26]
the introductory README states that for AWS an account is needed.  we should be specifying exactly which administrative powers are required for operating a K2 cluster.

**Comment by leahnp** [comment]
Should we go more granular than suggesting: 
* AmazonEC2FullAccess
* IAMFullAccess
* AmazonRoute53FullAccess
?

Does it make sense to compile all kraken/kraken-lib AWS commands and limit the policies to those actions? My concern about this is keeping the policy up to date moving forward.

I think to successfully maintain a minimum policy we would need to use this policy group for our CI, or at least run one test with the policy.

Finally, do we want to put the time into creating and maintaining this minimum IAM policy group or expect any user who wants tighter security do it themselves? @coffeepac

**Comment by philoserf** [comment]
We also could distinguish between rights needed to create a cluster and to operate. For example once VPCs are created those rights aren’t needed anymore for that cluster.

**Comment by leahnp** [comment]
@philoserf true - but wouldn't the VPC rights be needed again to delete a cluster? I need some direction on how much of an opinion we want on this subject ie: general policy suggestion just to get people started, minimum policy suggestion, creator AND operator, etc. @coffeepac

**Comment by philoserf** [comment]
True @leahnp I mention it because I am aware of places where temporary credentials with just enough power are required.

An operator may not want to have the power to destroy every day, all day long, in their primary shell sessions.

That said I think we start with the easier list of permissions and add context and nuisance as we can.

**Comment by leahnp** [comment]
Good idea @philoserf
