### ISSUE TITLE
k2cli should exit gracefully if it receives SIGINT

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken#64]
Currently k2cli will perform a hard exit if it receives SIGINT (Ctrl-C).  We should interpret Ctrl-C as the user intentionally terminating the application so we should perform a clean exit.

Or failing that we should ask the user if we want to perform a clean exit.

**Comment by coffeepac** [comment]
@spiffxp this issue is because you originally wanted to have the k2 container left around for forensics.  Is asking the user at SIGINT time sufficient?

**Comment by spiffxp** [comment]
This seems a weird dent for forensics. 

There is prior art for two ctrl-c's to mean "yes I really mean stop right now".  I think terraform?

But personally I think ctrl-c should kill without prompt.  If everyone else is finding forensics fine as is, I wouldn't bother to prompt.  Or maybe find an alternate way of keeping stuff around for forensics. Thinking of `docker run --rm` for prior art

**Comment by davidewatson** [comment]
+1 for keeping data and not prompting. What data are we losing when a Ctrl-C is received?

**Comment by coffeepac** [comment]
I have never needed the old container to stick around after execution.  I'm actually not sure what value it has.  There is no state saved to the container, there are no logs saved to the container.  

@davidewatson currently we lose no data when passing SIGINT to k2cli.  This causes problems because we are setting the container name which causes a conflict on the next k2cli execution with the same cluster config.

**Comment by spiffxp** [comment]
>wanted to have the k2 container left around for forensics

So, the dent is I modified containers to be named after the cluster they were creating.  And k2cli/docker aren't resilient to that.  Options:

1. revert my change, go back to containers being randomly named, rely on docker gc to clean up old containers
2. give k2cli some kind of "force" flag `-f` that means "yeah, go ahead and delete the old container that is named the same"
3. give k2cli some of of `--rm` flag (that I would default to false) that means "delete the container once the cluster has finished building/destroying/timed-out"

My use case is... 4 concurrent k2cli-based builds running in CLI.  One of them fails.  Can I get logs?

**Comment by spiffxp** [comment]
>There is no state saved to the container, there are no logs saved to the container.

If this is true, then yeah, nuke 'em.  I thought there was state.  If I run k2cli up, where are logs stored?  Where is terraform state stored?

**Comment by coffeepac** [comment]
for use case 4:  logs are written to stdout and aren't stored in the container.  you can get logs from whatever is executing k2cli. 

and if there are logs that aren't being written to stdout we should redirect those logs to stdout.

**Comment by coffeepac** [comment]
@spiffxp logs are written to stdout/stderr.  all other state is stored in a bind mounted directory that defaults to ~/.kraken/clusters and can be overridden with --output

**Comment by spiffxp** [comment]
you are correct sir, I have feverbrain please ignore

well, logs are dumped at the end, not streamed, so I wouldn't be able to look at an in-flight k2cli-based CI job to see what's taking so long

and a ctrl-c doesn't cause them to dump, so we probably ought to do that as part of "graceful" shutdown

we also have a `keep-alive` flag, which will rename the container to something random after completion (I find this behavior weird, but it's close to the `--rm` flag option)

**Comment by coffeepac** [comment]
which is better:
- SIGINT to flush logs and exit
- SIGINT to flush logs, requires two SIGINTs within 3 seconds to exit
- stream logs the entire time and SIGINT to exit

**Comment by spiffxp** [comment]
I am a big fan of "stream logs the entire time" either enabled by a `--verbose` flag or disabled via a `--quiet` flag

If that can't work, then I prefer SIGINT to flush logs and exit

two-sigint's only makes sense if we need a "graceful" shutdown pattern... is it just logs, or are there are other things that would be "nice" to do if interrupted?

**Comment by coffeepac** [comment]
I think I like:
- stream logs at all times unless '--quiet' is supplied
- '--verbose' gets passed through and increases verbosity
- the only cleanup we need to do is deleting/renaming the existing container

**Comment by coffeepac** [comment]
Ctrl-C, Ctrl-C for hard
Crl-c for sof\t
