### ISSUE TITLE
default behavior of k2cli when no cluster is specified

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/kraken#75]
when k2cli is run and no cluster is specified what should the default behavior be?  ie for `k2cli cluster up` should k2cli spin up all clusters listed in the config file, should it only spin up those labeled 'default' or should it do nothing and request the user specify which cluster or clusters to operate on.

**Comment by alejandroEsc** [comment]
Interesting story you have here in place. I suggest the following behavior:

- If config file has one cluster, and only one cluster it should spin that cluster up, or perform whatever tasks requested against that one cluster.
- if config file has more than one cluster, then it should stop operations until user decides on passing a --cluster-name flag to designate what cluster they are referring to.
