### ISSUE TITLE
make default display not be a spinner, but something that shows progress

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/kraken#81]
It would be nice to have several options for the k2cli output, especially on something like up and down.  Perhaps the default could be something like to show completed steps: 
_Status_
1) *etcd nodes built*
2) *etcd cluster established*
3) *control plane nodes built*
4) _API Service established_ (*in progress*)
5) _API ELB functional_
6) _Network Fabric established_
7) _KubeDNS deployed_
8) _Tiller Deployed_
9) _Services Deployed_
9a) _Kubernetes Dashboard_
9b) _fluentd_

There could also be a super pithy option of a terminal spinner like we have now, and then the options of verbose output.  

These articles offer some insight as to why our current setup of a spinner may not create the best user experience : 
* https://uxplanet.org/progress-indicators-in-mobile-ux-design-a141e22f3ea0
* http://uxmovement.com/navigation/progress-bars-vs-spinners-when-to-use-which/

**Comment by alejandroEsc** [comment]
Usually these types of things require some hooks to be added to the running code. For now all we have is output from stdout which we can show via verbosity. There is another ticket to make this verbose by default and silent as the optional thing. Which may take care of this issue or not. I am not sure how to hook the output into something kraken can pick up, but ill investigate.

**Comment by davidewatson** [comment]
This was fixed here: https://github.com/samsung-cnct/kraken/pull/181

**Comment by davidewatson** [comment]
Actually, this ticket is asking for something more than changing the spinner. Instead we would like more informational message regarding what the kraken command is doing at each step.
